# Generated by Django 5.0.4 on 2024-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(default='/static/img/default.jpg', upload_to='profile_pic'),
        ),
    ]
